### PR TITLE
Fix for nested nunjucks async shortcodes

### LINKED ISSUE #1053: Nunjucks: async shortcode inside paired shortcode
Hi Community!

**Describe the bug**
I want to use an async shortcode inside a paired shortcode. Unfortunately there is no content from the async shortcode (child) if it is inside the paired shortcode (parent). Standalone the async shortcode works. 

**To Reproduce**
I abstracted my code to this:

**Shortcodes (inside template file)**
```
{% parentPairedShortcode %}
  {% asyncChildShortcode %}
{% endparentPairedShortcode %}
```

**Config (.eleventy.js)**
```javascript
async function getSomething() {
  const promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("done!"), 1000)
  });
  const result = await promise;
  return result;
}

eleventyConfig.addNunjucksAsyncShortcode("asyncChildShortcode", async function() {
  const something = await getSomething();
  return something;
});

eleventyConfig.addPairedNunjucksAsyncShortcode("parentPairedShortcode", async function(content) {
  return content;
});
```

**Expected behavior**
Get the content of the async shortcode (child) paired shortcode back. I tried that with liquid shortcodes and it works. Did I do something wrong? Or did I forget something?

**Environment:**
- macOS 10.15.4 
- Eleventy v0.10.0

Please let me know if more information is needed. Thank you in advance.

### PR DESCRIPTION
**Pull request by CodeFoodPixels**
Nested async shortcodes would fail to correctly output content from the inner shortcode as eleventy wasn't waiting for the content to have processed before passing it to the parent.

The `body()` call takes a callback, which gets called when the passed content of a paired shortcode has finished rendering, both on async and sync templates.

Fixes #1053

### CODE REVIEW

File: src/Engines/Nunjucks.js [hunk 1]
```diff
@@ -287,57 +287,68 @@ class Nunjucks extends TemplateEngine {
         var body = parser.parseUntilBlocks("end" + shortcodeName);
         parser.advanceAfterBlockEnd();
 
-        if (isAsync) {
```
Comment (zachleat) [inline src/Engines/Nunjucks.js:290]: If I’m reading this right, this makes all Nunjucks paired shortcodes into Async shortcodes? Is this slower?

**Comment by CodeFoodPixels** [comment]
Thinking about it, this is probably an issue with Nunjucks itself

**Comment by CodeFoodPixels** [comment]
I've created a failing test and submitted it to Nunjucks: https://github.com/mozilla/nunjucks/issues/1363

**Comment by zachleat** [comment]
Maybe related https://github.com/11ty/eleventy-img/issues/110

**Comment by zachleat** [comment]
I’m interested in trying to fix this in Eleventy, if possible. I don’t think https://github.com/mozilla/nunjucks/pull/1357 is going to be enough, in local testing.

**Comment by zachleat** [comment]
Filed https://github.com/11ty/eleventy/issues/2108 which is now the home base issue for this PR, I think.

**Comment by zachleat** [comment]
This is a beautiful PR and I’m so sorry I slept on it for too long.

It doesn’t quite complete #2108 but it takes us a step in the correct direction.

As stated previously there may be _some_ (as of now untested) performance drawback to making everything async but we need to err on the side of correctness over performance here.

Shipping.

**Comment by zachleat** [comment]
This will ship with Beta 9

**Comment by zachleat** [comment]
For future me, note that the fix here was included in 1.0 stable but the async-everything approach was reverted in #2140.
